package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_ATTACK_MIN_DMG = 5
const PLAYER_ATTACK_MAX_DMG = 10
const PLAYER_ATTACK_SPEACIAL_MIN_DMG = 10
const PLAYER_ATTACK_SPEACIAL_MAX_DMG = 20
const PLAYER_HEAL_MIN = 5
const PLAYER_HEAL_MAX = 10

const MONSTER_ATTACK_MIN_DMG = 8
const MONSTER_ATTACK_MAX_DMG = 13